/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.starestarrysky

import java.io.File
import org.gradle.testkit.runner.GradleRunner
import kotlin.test.Test
import kotlin.test.assertTrue

/**
 * A simple functional test for the 'com.github.starestarrysky.site-gradle-plugin' plugin.
 */
class SiteGradlePluginFunctionalTest {
    @Test fun `can run task by groovy`() {
        // Setup the test build
        val projectDir = createBuildFile("groovy")
        projectDir.resolve("settings.gradle").writeText("")
        projectDir.resolve("build.gradle").writeText("""
            import com.github.starestarrysky.SiteTask

            plugins {
                id('com.github.starestarrysky.site-gradle-plugin')
            }

            github {
                credentials {
                    oauthToken = ''
                }
            }

            task site(type: SiteTask) {
                repositoryName = 'repository-test'
                repositoryOwner = 'StareStarrySky'
                branch = 'refs/heads/main'
                message = 'Repository-test for project.version.'
                outputDirectory = file('D:/IdeaProjects/site-gradle-plugin/plugin/build/libs')
                includes = ['**/*', ' ']
                excludes = ['plugin-1.0.0.jar']
            }
        """)

        // Run the build and verify the result
        runTask(projectDir)
    }

    @Test fun `can run task by kotlin`() {
        // Setup the test build
        val projectDir = createBuildFile("kotlin")
        projectDir.resolve("settings.gradle.kts").writeText("")
        projectDir.resolve("build.gradle.kts").writeText("""
            import com.github.starestarrysky.extension.GitHubExtension
            import com.github.starestarrysky.SiteTask

            plugins {
                id("com.github.starestarrysky.site-gradle-plugin")
            }

            configure<GitHubExtension> {
                credentials {
                    oauthToken = ""
                }
            }

            tasks.register<SiteTask>("site") {
                repositoryName.set("repository-test")
                repositoryOwner.set("StareStarrySky")
                branch.set("refs/heads/main")
                message.set("Repository-test for project.version.")
                outputDirectory.set(file("D:/IdeaProjects/site-gradle-plugin/plugin/build/libs"))
                includes.addAll("**/*", " ")
                excludes.addAll("plugin-1.0.0.jar")
            }
        """)

        // Run the build and verify the result
        runTask(projectDir)
    }

    /**
     * Setup the test build
     */
    private fun createBuildFile(lang: String): File {
        val projectDir = File("build/functionalTest/${lang}")
        projectDir.mkdirs()
        return projectDir
    }

    /**
     * Run the build and verify the result
     */
    private fun runTask(projectDir: File) {
        // Run the build
        val runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withArguments("site")
        runner.withProjectDir(projectDir)
        val result = runner.build()

        // Verify the result
        result.tasks.forEach { task -> assertTrue { task.outcome.name == "SUCCESS" } }
    }
}
