/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.starestarrysky

import com.github.starestarrysky.extension.GitHubExtension
import com.github.starestarrysky.tasks.GitHubCredentialsAware
import org.gradle.api.Action
import org.gradle.api.Project
import org.gradle.api.Plugin

/**
 * A simple 'hello world' plugin.
 */
class SiteGradlePlugin: Plugin<Project> {
    companion object {
        const val EXTENSION_NAME = "github"
    }

    override fun apply(project: Project) {
        val gitHubExtension = project.extensions.create(EXTENSION_NAME, GitHubExtension::class.java)
        project.tasks.withType(GitHubCredentialsAware::class.java).configureEach {
            Action<GitHubCredentialsAware> { task ->
                run {
                    task.gitHubCredentials.url = gitHubExtension.gitHubCredentials.url
                    task.gitHubCredentials.userName = gitHubExtension.gitHubCredentials.userName
                    task.gitHubCredentials.oauthAccessToken = gitHubExtension.gitHubCredentials.oauthAccessToken
                }
            }
        }
    }
}
